### ISSUE TITLE
Avenger's logo

### ISSUE THREAD

**Issue by Shiv-flexhub** [neelshah2409/Cartoonist#10]
Make Avenger's logo using python.
1. Ironman
2. Hulk
3. Captain America
4. Black Widow
5. Hawkeye
6. Black Panther
7. Thor

**Comment by neelshah2409** [comment]
Great idea !!
Go ahead 💫

**Comment by Shiv-flexhub** [comment]
created Thor's hammer Mjollnir using turtle library
`import turtle
import time
turtle.pensize(2)
turtle.color("silver")
turtle.pencolor("black")
turtle.begin_fill()
#turtle.speed(-2)
turtle.seth(-120)
turtle.forward(60)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(120)
turtle.left(45)
turtle.forward(10)
turtle.left(45)
turtle.forward(55)
turtle.left(45)
turtle.forward(10)
turtle.left(45)
turtle.forward(120)
turtle.left(45)
turtle.forward(10)
turtle.left(45)
turtle.forward(55)
#turtle.hideturtle()
turtle.left(45)
turtle.forward(10)
turtle.backward(10)
turtle.right(45)
turtle.backward(55)
turtle.right(45)
turtle.backward(10)
turtle.left(30)
turtle.backward(30)
turtle.left(105)
turtle.forward(105)
turtle.right(75)
turtle.forward(30)
turtle.left(35)
turtle.forward(10)
turtle.left(145)
turtle.forward(34)
turtle.left(45)
turtle.forward(8)
turtle.left(30)
turtle.forward(103)
turtle.left(30)
turtle.forward(10)
turtle.left(45)
#turtle.hideturtle()
turtle.forward(34)
turtle.backward(34)
turtle.left(135)
turtle.forward(10)
turtle.right(30)
turtle.forward(40)
turtle.right(90)
turtle.forward(20)
turtle.backward(180)
turtle.left(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(180)
turtle.hideturtle()
turtle.end_fill()
time.sleep(50)
turtle.done()` #

**Comment by neelshah2409** [comment]
@Shiv-flexhub make a proper pr of each logo separately 
and  don't write the code here

**Comment by sidling1** [comment]
can I do this ?

**Comment by neelshah2409** [comment]
> can I do this ?

Yes go ahead !!

**Comment by ShamanthVallem** [comment]
Can i take this issue??
