### ISSUE TITLE
Sort all files in folder

### ISSUE THREAD

**Issue by nik132-eng** [neelshah2409/Cartoonist#113]
![image](https://user-images.githubusercontent.com/77881638/210764830-3f535070-c329-4f5b-b76d-3ae56fe26c57.png)

**Comment by nik132-eng** [comment]
I want to make it in Different logos, cartoons, designs, etc.

**Comment by neelshah2409** [comment]
> I want to make it in Different logos, cartoons, designs, etc.

Go ahead !!
